services:
  postgres:
    container_name: postgres-insightlab
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'ilab#admin'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres
  
  pgadmin:
    container_name: pgadmin-insightlab
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@insightlab.com'
      PGADMIN_DEFAULT_PASSWORD: 'ilab#admin'
    ports:
      - 5433:80
    depends_on:
      - postgres
  
  # api:
  #   container_name: api-insightlab
  #   image: api-neuron5
  #   build: ./api
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - ./api/.env
  
  # spa:
  #   container_name: spa-neuron5
  #   image: spa-neuron5
  #   build: ./spa
  #   restart: always
  #   ports:
  #     - 3002:3002
  #   volumes:
  #     - spa-neuron5:/var/www/html
  #   depends_on:
  #     - api
  #   env_file:
  #     - ./spa/.env

  # nginx:
  #   container_name: nginx-neuron5
  #   image: nginx-neuron5
  #   build: ./nginx
  #   volumes:
  #     - spa-neuron5:/var/www/html
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - mysql
  #     - api
  #     - spa
    
volumes:
  database:

networks:
  default:
    name: insightlab-network
