services:
  postgres:
    container_name: postgres-insightlab
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'ilab#admin'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres
  
  pgadmin:
    container_name: pgadmin-insightlab
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@insightlab.com'
      PGADMIN_DEFAULT_PASSWORD: 'ilab#admin'
    ports:
      - 5433:80
    depends_on:
      - postgres
  
  api:
    container_name: api-insightlab
    image: api-insightlab
    build: ./api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  spa:
    container_name: spa-insightlab
    image: spa-insightlab
    build: ./spa
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file:
      - ./spa/.env

  # nginx:
  #   container_name: nginx-insightlab
  #   image: nginx-insightlab
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - postgres
  #     - api
  #     - spa
    
volumes:
  database:
  spa-insightlab:

networks:
  default:
    name: insightlab-network
